env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:astro/recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
  - "typescript-sort-keys"
  - "unused-imports"
  - "tailwindcss"
  - "jsx-a11y"
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
overrides:
  - files:
      - "*.astro"
    parser: "astro-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions:
        - ".astro"
